name = "pixel_splatter"
version = "1.0.0"


description = "A very simple gleam library to create windows and draw pixels for the erlang target"
licences = ["Apache-2.0"]
repository = { type = "github", user = "PastMoments", repo = "pixel_splatter" }

target = "erlang"

internal_modules = [
  "pixel_splatter/internal",
  "pixel_splatter/internal/*"
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
